name: lib5
description: Base library for S5.
version: 1.0.0-pre.1
homepage: https://lib5.dev

environment:
  sdk: ^3.0.0

dependencies:
  base_codecs: ^1.0.1
  convert: ^3.1.2
  http: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  s5_msgpack: ^0.3.0
  tint: ^2.0.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
