name: lib5
description: Base library for S5.
version: 0.2.0
homepage: https://lib5.dev

environment:
  sdk: ^3.0.0

dependencies:
  base_codecs: ^1.0.1
  convert: ^3.1.1
  http: ^1.0.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  s5_msgpack: ^0.3.0
  tint: ^2.0.1
  web_socket_channel: ^2.4.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
