name: lib5
description: Base library for S5.
version: 0.1.0
homepage: https://lib5.dev

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  base_codecs: ^1.0.1
  convert: ^3.1.1
  http: ^1.0.0
  http_parser: ^4.0.2
  messagepack:
    git: https://github.com/redsolver/messagepack.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
